---
- name: 'Instala pacotes de dependencia - MySQL'
  apt:
    name: ['mysql-server-5.6', 'python-mysqldb']
    state: latest
  become: yes

- name: 'Cria o banco do MySQL'
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: 'Cria o usuário do MySQL'
  community.mysql.mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{ wp_host_ip }}"

- name: 'Configura MySQL para aceitar conexões remotas'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql
